### 1. Import Dependencies

In [2]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### 2. Basic Processing

In [3]:
df = pd.read_csv("./data/processed/ChurnModeling_Outlier_Handled.csv")
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.00,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41.00,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42.00,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,38.91,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43.00,2,125510.82,1,1,1,79084.10,0

Credit Score
- 350 - 580 => 'Poor'
- 580 - 670 => 'Fair'
- 670 - 740 => 'Good'
- 740 - 800 => 'Very Good'
- 800+ => 'Excellent'

In [5]:
def custom_binning_creditscore(score):
    if score < 580:
        return 'Poor'
    elif score < 670:
        return 'Fair'
    elif score < 740:
        return 'Good'
    elif score < 800:
        return 'Very Good'
    elif score <= 850:
        return 'Excellent'
    else:
        assert True, "Credit Score can't go beyond 850"

df['CreditScoreBins'] = df['CreditScore'].apply(custom_binning_creditscore)

In [6]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins
0,619,France,Female,42.00,2,0.00,1,1,1,101348.88,1,Fair
1,608,Spain,Female,41.00,1,83807.86,1,0,1,112542.58,0,Fair
2,502,France,Female,42.00,8,159660.80,3,1,0,113931.57,1,Poor
3,699,France,Female,38.91,1,0.00,2,0,0,93826.63,0,Good
4,850,Spain,Female,43.00,2,125510.82,1,1,1,79084.10,0,Excellent

In [7]:
del df['CreditScore']

In [8]:
df.head()

,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins
0,France,Female,42.00,2,0.00,1,1,1,101348.88,1,Fair
1,Spain,Female,41.00,1,83807.86,1,0,1,112542.58,0,Fair
2,France,Female,42.00,8,159660.80,3,1,0,113931.57,1,Poor
3,France,Female,38.91,1,0.00,2,0,0,93826.63,0,Good
4,Spain,Female,43.00,2,125510.82,1,1,1,79084.10,0,Excellent

In [9]:
df.to_csv("./data/processed/ChurnModeling_Binning_Applied.csv", index=False)