### 1. Import Dependencies

In [28]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv("./data/processed/ChurnModeling_Binning_Applied.csv")
df.head()

,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins
0,France,Female,42.00,2,0.00,1,1,1,101348.88,1,Fair
1,Spain,Female,41.00,1,83807.86,1,0,1,112542.58,0,Fair
2,France,Female,42.00,8,159660.80,3,1,0,113931.57,1,Poor
3,France,Female,38.91,1,0.00,2,0,0,93826.63,0,Good
4,Spain,Female,43.00,2,125510.82,1,1,1,79084.10,0,Excellent

### 3. Encode Nominal Variables

In [30]:
geography_dummies = pd.get_dummies(df['Geography'], prefix='Geogeraphy')
geography_dummies

      Geogeraphy_France  Geogeraphy_Germany  Geogeraphy_Spain
0                  True               False             False
1                 False               False              True
2                  True               False             False
3                  True               False             False
4                 False               False              True
...                 ...                 ...               ...
9995               True               False             False
9996               True               False             False
9997               True               False             False
9998              False                True             False
9999               True               False             False

[10000 rows x 3 columns]

In [31]:
gender_dummies = pd.get_dummies(df['Gender'], prefix='Gender')
gender_dummies

      Gender_Female  Gender_Male
0              True        False
1              True        False
2              True        False
3              True        False
4              True        False
...             ...          ...
9995          False         True
9996          False         True
9997           True        False
9998          False         True
9999           True        False

[10000 rows x 2 columns]

In [32]:
df_encoded = pd.concat([df, geography_dummies], axis=1)
del df_encoded['Geography']

In [33]:
df_encoded

,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins,Geogeraphy_France,Geogeraphy_Germany,Geogeraphy_Spain
0,Female,42.00,2,0.00,1,1,1,101348.88,1,Fair,True,False,False
1,Female,41.00,1,83807.86,1,0,1,112542.58,0,Fair,False,False,True
2,Female,42.00,8,159660.80,3,1,0,113931.57,1,Poor,True,False,False
3,Female,38.91,1,0.00,2,0,0,93826.63,0,Good,True,False,False
4,Female,43.00,2,125510.82,1,1,1,79084.10,0,Excellent,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Male,39.00,5,0.00,2,1,0,96270.64,0,Very Good,True,False,False
9996,Male,35.00,10,57369.61,1,1,1,101699.77,0,Poor,True,False,False
9997,Female,36.00,7,0.00,1,0,1,42085.58,1,Good,True,False,False
9998,Male,42.00,3,75075.31,2,1,0,92888.52,1,Very Good,False,True,False
9999,Female,28.00,4,130142.79,1,1,0,38190.78,0,Very Good,True,False,False

In [34]:
df_encoded = pd.concat([df_encoded, gender_dummies], axis=1)
del df_encoded['Gender']

In [35]:
df_encoded

,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins,Geogeraphy_France,Geogeraphy_Germany,Geogeraphy_Spain,Gender_Female,Gender_Male
0,42.00,2,0.00,1,1,1,101348.88,1,Fair,True,False,False,True,False
1,41.00,1,83807.86,1,0,1,112542.58,0,Fair,False,False,True,True,False
2,42.00,8,159660.80,3,1,0,113931.57,1,Poor,True,False,False,True,False
3,38.91,1,0.00,2,0,0,93826.63,0,Good,True,False,False,True,False
4,43.00,2,125510.82,1,1,1,79084.10,0,Excellent,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,39.00,5,0.00,2,1,0,96270.64,0,Very Good,True,False,False,False,True
9996,35.00,10,57369.61,1,1,1,101699.77,0,Poor,True,False,False,False,True
9997,36.00,7,0.00,1,0,1,42085.58,1,Good,True,False,False,True,False
9998,42.00,3,75075.31,2,1,0,92888.52,1,Very Good,False,True,False,False,True
9999,28.00,4,130142.79,1,1,0,38190.78,0,Very Good,True,False,False,True,False

### 2. Encode Ordinal Variables

In [27]:
encode_dict_creditscore = {
    'Poor': 0,
    'Fair': 1,
    'Good': 2,
    'Very Good': 3,
    'Excellent': 4
}

df_encoded['CreditScoreBins'] = df_encoded['CreditScoreBins'].map(encode_dict_creditscore)
df_encoded.head()

,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins,Geogeraphy_France,Geogeraphy_Germany,Geogeraphy_Spain,Gender_Female,Gender_Male
0,42.00,2,0.00,1,1,1,101348.88,1,1,True,False,False,True,False
1,41.00,1,83807.86,1,0,1,112542.58,0,1,False,False,True,True,False
2,42.00,8,159660.80,3,1,0,113931.57,1,0,True,False,False,True,False
3,38.91,1,0.00,2,0,0,93826.63,0,2,True,False,False,True,False
4,43.00,2,125510.82,1,1,1,79084.10,0,4,False,False,True,True,False

In [37]:
df_encoded.to_csv("./data/processed/ChurnModeling_Feature_Encoding_Applied.csv", index=False)